name: Build Hel-Sync EXE

on:
  push:
    branches: [ "main" ] # أو اسم البرانش بتاعك

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # نسخة مستقرة

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pyqt5 qrcode pillow pyautogui cryptography pyopenssl pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        # --onefile: بيطلع ملف واحد
        # --windowed: عشان ميفتحش شاشة CMD سودة ورا البرنامج
        # --name: اسم الملف النهائي
        pyinstaller --onefile --windowed --name hel-sync main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hel-sync-windows-exe
        path: dist/hel-sync.exe
